### ISSUE TITLE
Feature request: add selected text to the message

### ISSUE THREAD

**Issue by nd-** [corbindavenport/share-to-mastodon#12]
Hello,

thanx for your extension, very usefull for a daily use.

It would be nice if the text selected on the page were added to the message, below the link to the page.
Some scriptlets do this with window.getSelection() but it sometimes causes errors on some sites.

**Comment by corbindavenport** [comment]
I don't think this is possible from the keyboard shortcut or toolbar button without adding more permissions, but it is already supported from the context menu. If you select text (instead of just right-clicking the page) and then choose Mastodon, the selection you quoted will replace the page title in the share box :)

![image](https://github.com/corbindavenport/share-to-mastodon/assets/3879063/4f71d4cc-f674-4632-b4aa-7b15d91242d4)

**Comment by nd-** [comment]
Oh yes, I never noticed that right click method, thanx.

And I see there's the same limit as when using a scriptlet: mastodon share urls (https://server.exemple/share?text=) send a 502 error if the text is longer than approximately 300 chararcters.

**Comment by corbindavenport** [comment]
Good to know, I've opened #13 for addressing that bug.
