### ISSUE TITLE
Feature request: Close button

### ISSUE THREAD

**Issue by sam1919** [corbindavenport/share-to-mastodon#8]
Hello,

thanks for your great extension Corbin!

I'd like to see a Close button.
Of course the window itself has a close icon but this is very small. But maybe it's just me. 😂

Thanks again!

**Comment by corbindavenport** [comment]
Unfortunately there's not a good way to implement this without adding more permissions, since the extension doesn't control how the share dialog looks (it's hosted by the mastodon server you choose). You can close the window with the `Control+W` keyboard shortcut though, or `Command+W` on Mac. Sorry about that!
